import enum

class TenantStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"

class UserStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"

class RoleCode(str, enum.Enum):
    ADMIN = "ADMIN"
    AP_CLERK = "AP_CLERK"
    PROCUREMENT_MANAGER = "PROCUREMENT_MANAGER"
    RECEIVING_USER = "RECEIVING_USER"
    FINANCE_MANAGER = "FINANCE_MANAGER"
    FINANCE_HEAD = "FINANCE_HEAD"
    AUDITOR = "AUDITOR"

class VendorStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    BLOCKED = "BLOCKED"
    PENDING_VERIFICATION = "PENDING_VERIFICATION"

class VendorRiskStatus(str, enum.Enum):
    NORMAL = "NORMAL"
    REVIEW = "REVIEW"
    HIGH_RISK = "HIGH_RISK"

class POStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"
    FULLY_RECEIVED = "FULLY_RECEIVED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"

class ReceiptStatus(str, enum.Enum):
    PENDING = "PENDING"
    PARTIAL = "PARTIAL"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"

class InvoiceStatus(str, enum.Enum):
    RECEIVED = "RECEIVED"
    PROCESSING = "PROCESSING"
    VALIDATING = "VALIDATING"
    EXCEPTION = "EXCEPTION"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PAYABLE_CREATED = "PAYABLE_CREATED"
    PAID = "PAID"
    CANCELLED = "CANCELLED"

class ExtractionStatus(str, enum.Enum):
    NOT_STARTED = "NOT_STARTED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    MANUAL_REVIEW = "MANUAL_REVIEW"

class ControlRunStatus(str, enum.Enum):
    RUNNING = "RUNNING"
    PASSED = "PASSED"
    FAILED = "FAILED"
    PARTIAL = "PARTIAL"
    ERROR = "ERROR"

class ControlCategory(str, enum.Enum):
    VENDOR = "VENDOR"
    PROCUREMENT = "PROCUREMENT"
    RECEIPT = "RECEIPT"
    FINANCIAL = "FINANCIAL"
    DUPLICATE = "DUPLICATE"
    APPROVAL = "APPROVAL"
    SECURITY = "SECURITY"

class ControlCode(str, enum.Enum):
    VENDOR_EXISTS = "VENDOR_EXISTS"
    VENDOR_STATUS = "VENDOR_STATUS"
    VENDOR_TAX_ID_MATCH = "VENDOR_TAX_ID_MATCH"
    PO_EXISTS = "PO_EXISTS"
    PO_APPROVED = "PO_APPROVED"
    PO_VENDOR_MATCH = "PO_VENDOR_MATCH"
    PO_ITEM_MATCH = "PO_ITEM_MATCH"
    QUANTITY_MATCH = "QUANTITY_MATCH"
    RECEIPT_MATCH = "RECEIPT_MATCH"
    PRICE_MATCH = "PRICE_MATCH"
    TAX_VALIDATION = "TAX_VALIDATION"
    TOTAL_VALIDATION = "TOTAL_VALIDATION"
    PAYMENT_TERMS_VALIDATION = "PAYMENT_TERMS_VALIDATION"
    DUPLICATE_EXACT = "DUPLICATE_EXACT"
    DUPLICATE_SEMANTIC = "DUPLICATE_SEMANTIC"
    BANK_DETAILS_MATCH = "BANK_DETAILS_MATCH"

class ControlStatus(str, enum.Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    WARNING = "WARNING"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    ERROR = "ERROR"

class SeverityLevel(str, enum.Enum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class RiskSignalStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    RESOLVED = "RESOLVED"
    DISMISSED = "DISMISSED"

class ExceptionStatus(str, enum.Enum):
    OPEN = "OPEN"
    IN_REVIEW = "IN_REVIEW"
    WAITING_FOR_INFORMATION = "WAITING_FOR_INFORMATION"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"

class ApprovalStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SKIPPED = "SKIPPED"
    CANCELLED = "CANCELLED"

class ApprovalDecision(str, enum.Enum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    REQUEST_CHANGES = "REQUEST_CHANGES"

class PayableStatus(str, enum.Enum):
    OPEN = "OPEN"
    PARTIALLY_PAID = "PARTIALLY_PAID"
    PAID = "PAID"
    ON_HOLD = "ON_HOLD"
    CANCELLED = "CANCELLED"

class PaymentStatus(str, enum.Enum):
    SCHEDULED = "SCHEDULED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REVERSED = "REVERSED"
